
# Overzicht Estuariene Natuurontwikkelingsprojecten 

__Gunther Van Ryckegem__

## Inleiding
In dit hoofdstuk wordt op vraag van de projectgroep Monitoring en Databeheer een overzicht gegeven van de natuurontwikkelingsprojecten die reeds uitgevoerd zijn in de Zeeschelde, met weergave van de voornaamste karakteristieken van het gebied. Onderstaande informatie is beschikbaar gemaakt via het online portaal http://www.abpmer.net/omreg/. Deze website omvat een databank met uitgevoerde estuariene natuurontwikkelingsprojecten.

Voor details over de uitvoering en de initiele evoluties in de ontpolderingen wordt verwezen naar @vandenneuckerEvaluatieVanNatuurontwikkelingsprojecten2007 en **XXX**. De evoluties in de GGG’s[^footnote-020-1] worden opgevolgd door Universiteit Antwerpen (**XXX**). In totaal werd er sinds 2003 ruim 450 ha aan estuariene natuurontwikkeling gerealiseerd (Tabel \@ref(tab:020-tabel-natuurontwikkelingsprojecten)).

[^footnote-020-1]: Gecontroleerd Gereduceerd Getijdengebied


```{r 020-tabel-natuurontwikkelingsprojecten}

tabel_natuurontwikkelingsprojecten <- read_excel("../tabellen/020_Overzicht_tabellen.xlsx", 
    sheet = "natuurontwikkelingsprojecten", .name_repair = "minimal")

# tabel_natuurontwikkelingsprojecten <- read_excel("~/moneos-test/moneos_2020_test/tabellen/020_Overzicht_tabellen.xlsx", 
#     sheet = "natuurontwikkelingsprojecten", .name_repair = "minimal")

options(knitr.kable.NA = '')

tabel_natuurontwikkelingsprojecten[c(5,7),3] <- sapply(tabel_natuurontwikkelingsprojecten[c(5,7),3], 
                                                       function(x) paste0(x, footnote_marker_number(1)))

tabel_natuurontwikkelingsprojecten[c(7,12,13),4] <- sapply(tabel_natuurontwikkelingsprojecten[c(7,12,13),4], 
                                                       function(x) paste0(x, footnote_marker_number(2)))

tabel_natuurontwikkelingsprojecten[13,4] <- paste0(tabel_natuurontwikkelingsprojecten[13,4],
                                                   "\\textsuperscript{,}",
                                                   footnote_marker_number(3))


tabel_natuurontwikkelingsprojecten %>% 
  knitr::kable(caption = "Overzicht van de uitgevoerde estuariene natuurontwikkelingsprojecten langsheen de Zeeschelde en zijrivieren. De gebieden staan gerangschikt van grens BE-NL stroomopwaarts.",
             # "latex", 
             booktabs = T,
             escape = F) %>% 
    kable_styling(latex_options = c("scale_down"),
                  font_size = 12) %>%
  footnote(number = c("met koker verbonden (natuurlijk getijpatroon en dynamiek is beïnvloed)", 
                       "oppervlakte ecotopenkaart 2016",
                       "in de loop van 2017 werd nog een grondstock opgeruimd en toegevoegd aan de ontpoldering (+ 2.2 ha)"),
           threeparttable = TRUE)

```



## Estuariene natuurontwikkeling Schelde-estuarium

In 2017 werden enkele grote projecten gerealiseerd: KBR werd volledig functioneel met de opening van GGG Kruibeke, Kruibeke kreek en de ontpoldering van de Fasseitpolder. Ook de opening van het GGG Zennegat is een belangrijke realisatie nabij de monding van de Dijle en Zenne.
